# Generated by Django 5.2.12 on 2026-04-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cr', 'vegetables'), ('ml', 'Fruits'), ('ls', 'LiveStocks'), ('ms', 'Equipments'), ('pn', 'Animal Feeds'), ('gh', 'Seeds'), ('cz', 'Pesticides'), ('ic', 'Vetrinary Medicines'), ('fc', 'Fertilzers'), ('hm', 'hom')], max_length=2),
        ),
    ]
